const actionTypes = {
  // init game
  INIT_GAME: "INIT_GAME",
  GET_FIELD_SIZE: "GET_FIELD_SIZE",
  SET_FIELD_SIZE: "SET_FIELD_SIZE",
  LOADING_SCORE: "LOADING_SCORE",
  SET_USERNAME: "SET_USERNAME",

  // gameplay
  CARD_CLICK: "CARD_CLICK",
  FLIP_CARD: "FLIP_CARD",
  GET_CARDS: "GET_CARDS",
  GET_CARD: "GET_CARD",
  GET_MATCHED_CARDS: "GET_MATCHED_CARDS",
  RESET_STATE: "RESET_STATE",
};

export default actionTypes;
